networks:
  iii_net:
    ipam:
      config:
      - subnet: 172.28.0.0/16
      driver: default
services:
  hadoop:
    container_name: wei_hadoop
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    environment:
    - NODE_TYPE=master
    expose:
    - '50070'
    - '9000'
    hostname: master
    image: orozcohsu/ha-sp-ze-zo-hi-fl-rs-ma-sq
    networks:
      iii_net:
        ipv4_address: 172.28.1.3
    ports:
    - 8088:8088
    - 50070:50070
    - 9000:9000
    - '2222:22'
    - 28080:28080
    - 18080:18080
    - 10000:10000
    - 10002:10002
    - 9083:9083
    - 3306:3306
    volumes:
    - /tmp/docker-cluster-hadoop-name/:/data/dfs/name/
    - /tmp/docker-cluster-hadoop-data/:/data/dfs/data/
    - /tmp/docker-cluster-hadoop-logs/:/usr/local/hadoop/logs/
    - /tmp/docker-cluster-zookeeper-logs/:/var/log/zookeeper/
    - /tmp/docker-cluster-zeppelin-logs/:/usr/local/zeppelin/log
    - nvidia_driver_418.87.00:/usr/local/nvidia:ro
  jupyter:
    build:
      context: ./dockerfile
      dockerfile: dockerfile-jupyter
    command: start-notebook.sh --NotebookApp.token=''
    container_name: wei_jupyter
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    expose:
    - '8888'
    hostname: jupyter
    networks:
      iii_net:
        ipv4_address: 172.28.1.2
    ports:
    - 8889:8888
    - 5001:5000
    volumes:
    - /iii/jupyter:/home/jovyan/webhook-dev
    - nvidia_driver_418.87.00:/usr/local/nvidia:ro
  openpose:
    container_name: wei_openpose
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    expose:
    - '8888'
    hostname: openpose
    image: moonlight165/wei_openpose
    networks:
      iii_net:
        ipv4_address: 172.28.1.4
    ports:
    - 8890:8888
    tty: true
    volumes:
    - /home/weiclass/Tibame_project/picture:/openpose-master/openpose/picture
    - nvidia_driver_418.87.00:/usr/local/nvidia:ro
  pytorch:
    container_name: wei_pytorch
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    expose:
    - '8888'
    hostname: pytorch
    image: moonlight165/wei_pytorch
    networks:
      iii_net:
        ipv4_address: 172.28.1.5
    ports:
    - 8891:8888
    tty: true
    volumes:
    - /home/weiclass/Tibame_project/picture:/openpose-master/pytorch/picture
    - nvidia_driver_418.87.00:/usr/local/nvidia:ro
version: '3.7'
volumes:
  nvidia_driver_418.87.00:
    external: true
